### ISSUE TITLE
Links in README are broken

### ISSUE THREAD

**Issue by airon90** [beniz/seeks#1]
All links to wiki in README file are broken because the main website ceased to exist.

**Comment by beniz** [comment]
Fixed.

**Comment by Kasijjuf** [comment]
@beniz You missed a link. Check the second line of the README.
